const jhsData = {
    jhs_iwork_english3: {
        id: "jhs_iwork_english3",
        title: "iワーク 中3英語",
        totalPages: 390,
        imagesPath: "images/jhs_iwork_english3/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_iwork_english3_cover.jpg",
        qrBase: "",
        chapters: [
            { id: "cover", title: "表紙", start: 1, end: 1, subsections: [] },
            { id: "main", title: "中3英語（本冊）", start: 2, end: 184, subsections: [
                { num: "復習1", title: "中1, 中2の復習①", page: 4 },
                { num: "復習2", title: "中1, 中2の復習②", page: 6 },
                { num: "復習3", title: "中1, 中2の復習③", page: 8 },
                { num: "復習4", title: "中1, 中2の復習④", page: 10 },
                { num: "復習5", title: "中1, 中2の復習⑤", page: 12 },
                { num: 6,  title: "PROG.1 新出単語・重要表現", page: 13 },
                { num: 7,  title: "PROG.1 ①（ask[tell/want]~to...）", page: 14 },
                { num: 8,  title: "PROG.1 ②（It is ~ for+人 to...）", page: 16 },
                { num: 9,  title: "PROG.1 ③（現在完了・経験）", page: 18 },
                { num: 10, title: "PROG.1 定期テスト対策A", page: 20 },
                { num: 11, title: "PROG.1 定期テスト対策B", page: 22 },
                { num: 13, title: "PROG.2 新出単語・重要表現", page: 25 },
                { num: 14, title: "PROG.2 ①（現在完了・完了）", page: 26 },
                { num: 15, title: "PROG.2 ②（現在完了・継続）", page: 28 },
                { num: 16, title: "PROG.2 ③（現在完了進行形）", page: 30 },
                { num: 17, title: "PROG.2 定期テスト対策A", page: 32 },
                { num: 18, title: "PROG.2 定期テスト対策B", page: 34 },
                { num: 21, title: "PROG.3 新出単語・重要表現", page: 39 },
                { num: 22, title: "PROG.3 ①（SVthat）", page: 40 },
                { num: 23, title: "PROG.3 ②（SVOC）", page: 42 },
                { num: 24, title: "PROG.3 ③（SVOC+原形）", page: 44 },
                { num: 25, title: "PROG.3 定期テスト対策A", page: 46 },
                { num: 26, title: "PROG.3 定期テスト対策B", page: 48 },
                { num: 29, title: "言語活動① 新出単語・重要表現", page: 53 },
                { num: 30, title: "言語活動① Power-Up 1 / Step 2", page: 54 },
                { num: 31, title: "言語活動① Our Project 1", page: 55 },
                { num: 32, title: "言語活動① Reading 1 Meaning of Life ①", page: 56 },
                { num: 37, title: "言語活動① 定期テスト対策A", page: 61 },
                { num: 43, title: "PROG.4 新出単語・重要表現", page: 67 },
                { num: 44, title: "PROG.4 ①（分詞の後置修飾・現在分詞）", page: 68 },
                { num: 45, title: "PROG.4 ②（分詞の後置修飾・過去分詞）", page: 70 },
                { num: 46, title: "PROG.4 ③（間接疑問文）", page: 72 },
                { num: 47, title: "PROG.4 定期テスト対策A", page: 74 },
                { num: 48, title: "PROG.4 定期テスト対策B", page: 76 },
                { num: 50, title: "PROG.5 新出単語・重要表現", page: 79 },
                { num: 51, title: "PROG.5 ①（関係代名詞主格 who）", page: 80 },
                { num: 52, title: "PROG.5 ②（関係代名詞主格 which）", page: 82 },
                { num: 53, title: "PROG.5 ③（関係代名詞主格 that）", page: 84 },
                { num: 54, title: "PROG.5 定期テスト対策A", page: 86 },
                { num: 55, title: "PROG.5 定期テスト対策B", page: 88 },
                { num: 57, title: "言語活動② 新出単語・重要表現", page: 91 },
                { num: 58, title: "言語活動② Power-Up 2", page: 92 },
                { num: 60, title: "言語活動② 定期テスト対策A", page: 94 },
                { num: 64, title: "PROG.6 新出単語・重要表現", page: 99 },
                { num: 65, title: "PROG.6 ①（関係代名詞目的格 which）", page: 100 },
                { num: 66, title: "PROG.6 ②（関係代名詞目的格 that）", page: 102 },
                { num: 67, title: "PROG.6 ③（関係代名詞の省略）", page: 104 },
                { num: 68, title: "PROG.6 定期テスト対策A", page: 106 },
                { num: 69, title: "PROG.6 定期テスト対策B", page: 108 },
                { num: 72, title: "言語活動③ 新出単語・重要表現", page: 113 },
                { num: 73, title: "言語活動③ Our Project 2", page: 114 },
                { num: 75, title: "言語活動③ 定期テスト対策A", page: 116 },
                { num: 79, title: "PROG.7 新出単語・重要表現", page: 121 },
                { num: 80, title: "PROG.7 ①（仮定法過去・be動詞）", page: 122 },
                { num: 81, title: "PROG.7 ②（仮定法過去・一般動詞）", page: 124 },
                { num: 82, title: "PROG.7 ③（I wish + 過去形）", page: 126 },
                { num: 83, title: "PROG.7 定期テスト対策A", page: 128 },
                { num: 84, title: "PROG.7 定期テスト対策B", page: 130 },
                { num: 87, title: "言語活動④ 新出単語・重要表現", page: 135 },
                { num: 89, title: "言語活動④ Reading 2 Malala's Voice ①", page: 137 },
                { num: 94, title: "言語活動④ 定期テスト対策A", page: 142 },
                { num: 99, title: "言語活動⑤ Further Reading 1", page: 150 },
                { num: 106, title: "言語活動⑥ Further Reading 2", page: 158 },
                { num: 113, title: "言語活動⑦ Further Reading 3", page: 166 },
                { num: "付録", title: "付録（Word Web・重要例文・不規則動詞活用表・比較変化表）", page: 175 }
            ] },
            { id: "main_answers", title: "中3英語 解答解説", start: 185, end: 274, subsections: [] },
            { id: "plus", title: "iワークプラス", start: 275, end: 352, subsections: [] },
            { id: "plus_answers", title: "iワークプラス 解答解説", start: 353, end: 390, subsections: [] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_iwork_english2: {
        id: "jhs_iwork_english2",
        title: "iワーク 中2英語",
        totalPages: 371,
        imagesPath: "images/jhs_iwork_english2/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_iwork_english2_cover.jpg",
        qrBase: "",
        chapters: [
            { id: "cover", title: "表紙", start: 1, end: 1, subsections: [] },
            { id: "main", title: "中2英語（本冊）", start: 2, end: 176, subsections: [
                { num: "復習1", title: "中1の復習①", page: 4 },
                { num: "復習2", title: "中1の復習②", page: 6 },
                { num: "復習3", title: "中1の復習③", page: 8 },
                { num: "復習4", title: "中1の復習④", page: 10 },
                { num: "復習5", title: "中1の復習⑤", page: 12 },
                { num: 6,  title: "PROG.1 新出単語・重要表現", page: 13 },
                { num: 7,  title: "PROG.1 ①Scenes / Part（be going to ~）", page: 14 },
                { num: 8,  title: "PROG.1 ②Scenes / Part（will）", page: 16 },
                { num: 9,  title: "PROG.1 ③Scenes / Part（動名詞）", page: 18 },
                { num: 10, title: "PROG.1 定期テスト対策A", page: 20 },
                { num: 11, title: "PROG.1 定期テスト対策B", page: 22 },
                { num: 13, title: "PROG.2 新出単語・重要表現", page: 25 },
                { num: 14, title: "PROG.2 ①Scenes / Part（接続詞 that）", page: 26 },
                { num: 15, title: "PROG.2 ②Scenes / Part（接続詞 when）", page: 28 },
                { num: 16, title: "PROG.2 ③Scenes / Part（if / because）", page: 30 },
                { num: 17, title: "PROG.2 定期テスト対策A", page: 32 },
                { num: 18, title: "PROG.2 定期テスト対策B", page: 34 },
                { num: 21, title: "言語活動① 新出単語・重要表現", page: 39 },
                { num: 22, title: "言語活動① Power-Up 1 / Step 2", page: 40 },
                { num: 26, title: "PROG.3 新出単語・重要表現", page: 45 },
                { num: 27, title: "PROG.3 ①Scenes / Part（不定詞 名詞的）", page: 46 },
                { num: 28, title: "PROG.3 ②Scenes / Part（不定詞 副詞的）", page: 48 },
                { num: 29, title: "PROG.3 ③Scenes / Part（不定詞 形容詞的）", page: 50 },
                { num: 30, title: "PROG.3 定期テスト対策A", page: 52 },
                { num: 31, title: "PROG.3 定期テスト対策B", page: 54 },
                { num: 33, title: "言語活動② 新出単語・重要表現", page: 57 },
                { num: 35, title: "言語活動② Reading 1 The Three Dolls ①", page: 59 },
                { num: 38, title: "言語活動② Power-Up 2 電話をかけよう", page: 62 },
                { num: 43, title: "PROG.4 新出単語・重要表現", page: 69 },
                { num: 44, title: "PROG.4 ①Scenes / Part（感情の原因の不定詞）", page: 70 },
                { num: 45, title: "PROG.4 ②Scenes / Part（must）", page: 72 },
                { num: 46, title: "PROG.4 ③Scenes / Part（have to ~）", page: 74 },
                { num: 47, title: "PROG.4 定期テスト対策A", page: 76 },
                { num: 48, title: "PROG.4 定期テスト対策B", page: 78 },
                { num: 52, title: "言語活動③ 新出単語・重要表現", page: 85 },
                { num: 53, title: "言語活動③ Power-Up 3 / Step 3", page: 86 },
                { num: 57, title: "PROG.5 新出単語・重要表現", page: 91 },
                { num: 58, title: "PROG.5 ①Scenes / Part（how to ~）", page: 92 },
                { num: 59, title: "PROG.5 ②Scenes / Part（look+形容詞）", page: 94 },
                { num: 60, title: "PROG.5 ③Scenes / Part（動詞+人+もの）", page: 96 },
                { num: 61, title: "PROG.5 定期テスト対策A", page: 98 },
                { num: 62, title: "PROG.5 定期テスト対策B", page: 100 },
                { num: 65, title: "PROG.6 新出単語・重要表現", page: 105 },
                { num: 66, title: "PROG.6 ①Scenes / Part（比較級）", page: 106 },
                { num: 67, title: "PROG.6 ②Scenes / Part（最上級）", page: 108 },
                { num: 68, title: "PROG.6 ③Scenes / Part（as ~ as）", page: 110 },
                { num: 69, title: "PROG.6 定期テスト対策A", page: 112 },
                { num: 70, title: "PROG.6 定期テスト対策B", page: 114 },
                { num: 72, title: "言語活動④ 新出単語・重要表現", page: 117 },
                { num: 76, title: "言語活動④ Reading 2 Friendship ①", page: 121 },
                { num: 83, title: "PROG.7 新出単語・重要表現", page: 129 },
                { num: 84, title: "PROG.7 ①Scenes / Part（like ~ better）", page: 130 },
                { num: 85, title: "PROG.7 ②Scenes / Part（like ~ best）", page: 132 },
                { num: 86, title: "PROG.7 ③Scenes / Part（teach+人+how to）", page: 134 },
                { num: 87, title: "PROG.7 定期テスト対策A", page: 136 },
                { num: 88, title: "PROG.7 定期テスト対策B", page: 138 },
                { num: 91, title: "PROG.8 新出単語・重要表現", page: 143 },
                { num: 92, title: "PROG.8 ①Scenes / Part（受け身）", page: 144 },
                { num: 93, title: "PROG.8 ②Scenes / Part（by ~ の受け身）", page: 146 },
                { num: 94, title: "PROG.8 ③Scenes / Part（前置詞を使う受け身）", page: 148 },
                { num: 95, title: "PROG.8 定期テスト対策A", page: 150 },
                { num: 96, title: "PROG.8 定期テスト対策B", page: 152 },
                { num: 99, title: "言語活動⑤ 新出単語・重要表現", page: 157 },
                { num: 103, title: "言語活動⑤ Reading 3 Apollo 13 ①", page: 161 },
                { num: 106, title: "言語活動⑤ 定期テスト対策A", page: 164 },
                { num: 107, title: "言語活動⑤ 定期テスト対策B", page: 165 },
                { num: "付録", title: "付録（Word Web・重要例文・不規則動詞活用表・比較変化表）", page: 169 }
            ] },
            { id: "main_answers", title: "中2英語 解答解説", start: 177, end: 265, subsections: [] },
            { id: "plus", title: "iワークプラス", start: 266, end: 337, subsections: [] },
            { id: "plus_answers", title: "iワークプラス 解答解説", start: 338, end: 371, subsections: [] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_iwork_english1: {
        id: "jhs_iwork_english1",
        title: "iワーク 中1英語",
        totalPages: 372,
        imagesPath: "images/jhs_iwork_english1/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_iwork_english1_cover.jpg",
        qrBase: "",
        chapters: [
            { id: "cover", title: "表紙", start: 1, end: 1, subsections: [] },
            { id: "main", title: "中1英語（本冊）", start: 2, end: 180, subsections: [
                { num: 1,    title: "新出単語・重要表現", page: 4 },
                { num: 2,    title: "Get Ready 1, 2　町の中の会話を聞こう / 英語すごろくをしよう", page: 5 },
                { num: 10,   title: "PROGRAM 1 ① Scenes 1 / Part 1", page: 14 },
                { num: 11,   title: "PROGRAM 1 ② Scenes 2 / Part 2 / Action / 英語早わかり", page: 16 },
                { num: 12,   title: "PROGRAM 1 定期テスト対策A", page: 18 },
                { num: 16,   title: "PROGRAM 2 ① Scenes 1 / Part 1", page: 24 },
                { num: 17,   title: "PROGRAM 2 ② Scenes 2 / Part 2 / Action / 英語早わかり", page: 26 },
                { num: 44,   title: "PROGRAM 5 ① Scenes 1 / Part 1", page: 68 },
                { num: 45,   title: "PROGRAM 5 ② Scenes 2 / Part 2 / Review / Action / 英語早わかり", page: 70 },
                { num: 88,   title: "PROGRAM 9 ① Scenes 1 / Part 1", page: 134 },
                { num: 89,   title: "PROGRAM 9 ② Scenes 2 / Part 2", page: 136 },
                { num: 90,   title: "PROGRAM 9 ③ Scenes 3 / Part 3 / Review & Retell / Action / 英語早わかり", page: 138 },
                { num: "付録", title: "付録（Word Web・不規則動詞活用表・重要例文）", page: 173 }
            ] },
            { id: "main_answers", title: "中1英語 解答解説", start: 181, end: 268, subsections: [] },
            { id: "plus", title: "iワークプラス", start: 269, end: 339, subsections: [] },
            { id: "plus_answers", title: "iワークプラス 解答解説", start: 340, end: 372, subsections: [] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_iwork_science3: {
        id: "jhs_iwork_science3",
        title: "iワーク 中3理科",
        totalPages: 434,
        imagesPath: "images/jhs_iwork_science3/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_iwork_science3_cover.jpg",
        qrBase: "",
        chapters: [
            { id: "cover", title: "表紙", start: 1, end: 1, subsections: [] },
            { id: "main", title: "中3理科（本冊）", start: 2, end: 233, subsections: [
                { num: 1, title: "いろいろな生物とその共通点", page: 5 },
                { num: 2, title: "活きている地球", page: 9 },
                { num: 3, title: "身のまわりの物質", page: 13 },
                { num: 4, title: "光・音・力による現象", page: 17 },
                { num: 5, title: "生物の体のつくりとはたらき", page: 21 },
                { num: 6, title: "地球の大気と天気の変化", page: 25 },
                { num: 7, title: "化学変化と原子・分子", page: 29 },
                { num: 8, title: "電流とその利用", page: 33 },
                { num: 9, title: "生物のふえ方と成長", page: 37 },
                { num: 10, title: "遺伝の規則性と遺伝子", page: 41 },
                { num: 11, title: "生物の種類の実多様性と進化", page: 45 },
                { num: 12, title: "宇宙の天体", page: 63 },
                { num: 13, title: "太陽の動き", page: 67 },
                { num: 14, title: "星座の星の動き", page: 73 },
                { num: 15, title: "月と金星の動きと見え方", page: 77 },
                { num: 16, title: "水溶液とイオン", page: 99 },
                { num: 17, title: "電池とイオン", page: 105 },
                { num: 18, title: "酸とアルカリ", page: 111 },
                { num: 19, title: "中和と塩", page: 115 },
                { num: 20, title: "水中の物体にはたらく力", page: 139 },
                { num: 21, title: "力の合成と分解", page: 143 },
                { num: 22, title: "物体の運動", page: 147 },
                { num: 23, title: "水平面上での物体の運動", page: 155 },
                { num: 24, title: "斜面上の物体の運動", page: 159 },
                { num: 25, title: "仕事", page: 169 },
                { num: 26, title: "エネルギー", page: 175 },
                { num: 27, title: "多様なエネルギーとその移り変わり", page: 181 },
                { num: 28, title: "エネルギー資源とその利用", page: 185 },
                { num: 29, title: "生物どうしのつながり", page: 209 },
                { num: 30, title: "生物の遺骸のゆくえと物質の循環", page: 213 },
                { num: 31, title: "自然と人間", page: 217 },
                { num: "資料", title: "元素周期表", page: 233 }
            ] },
            { id: "main_answers", title: "中3理科 解答解説", start: 234, end: 315, subsections: [] },
            { id: "plus", title: "iワークプラス", start: 316, end: 409, subsections: [] },
            { id: "plus_answers", title: "iワークプラス 解答解説", start: 410, end: 434, subsections: [] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_iwork_science2: {
        id: "jhs_iwork_science2",
        title: "iワーク 中2理科",
        totalPages: 426,
        imagesPath: "images/jhs_iwork_science2/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_iwork_science2_cover.jpg",
        qrBase: "",
        chapters: [
            { id: "cover", title: "表紙", start: 1, end: 1, subsections: [] },
            { id: "main", title: "中2理科（本冊）", start: 2, end: 233, subsections: [
                { num: 1, title: "いろいろな生物とその共通点", page: 5 },
                { num: 2, title: "活きている地球", page: 9 },
                { num: 3, title: "身のまわりの物質", page: 13 },
                { num: 4, title: "光・音・力による現象", page: 17 },
                { num: 5, title: "生物の体をつくるもの", page: 21 },
                { num: 6, title: "光合成と呼吸", page: 25 },
                { num: 7, title: "根と茎のつくり", page: 31 },
                { num: 8, title: "葉のつくりとはたらき", page: 35 },
                { num: 9, title: "栄養分をとり入れるしくみ", page: 41 },
                { num: 10, title: "動物の呼吸", page: 45 },
                { num: 11, title: "動物の行動のしくみ", page: 49 },
                { num: 12, title: "大気の中ではたらく力", page: 73 },
                { num: 13, title: "気象観測", page: 77 },
                { num: 14, title: "雲のでき方", page: 83 },
                { num: 15, title: "空気中にふくまれる水蒸気の量", page: 87 },
                { num: 16, title: "気圧配置と天気の変化", page: 95 },
                { num: 17, title: "大気の動き", page: 99 },
                { num: 18, title: "日本の天気", page: 105 },
                { num: 19, title: "物質の分解", page: 125 },
                { num: 20, title: "物質の成り立ち", page: 129 },
                { num: 21, title: "物質どうしが結びつく変化", page: 137 },
                { num: 22, title: "酸化と還元", page: 141 },
                { num: 23, title: "化学変化と熱の出入り", page: 145 },
                { num: 24, title: "化学変化の前後の物質の質量", page: 153 },
                { num: 25, title: "反応する物質どうしの質量の割合", page: 157 },
                { num: 26, title: "回路と電流・電圧", page: 181 },
                { num: 27, title: "電圧と電流の関係", page: 187 },
                { num: 28, title: "電流のはたらきを表す量", page: 193 },
                { num: 29, title: "電流の正体", page: 201 },
                { num: 30, title: "電流がつくる磁界", page: 205 },
                { num: 31, title: "発電機のしくみ", page: 209 },
                { num: "資料", title: "元素周期表", page: 233 }
            ] },
            { id: "main_answers", title: "中2理科 解答解説", start: 234, end: 307, subsections: [] },
            { id: "plus", title: "iワークプラス", start: 308, end: 401, subsections: [] },
            { id: "plus_answers", title: "iワークプラス 解答解説", start: 402, end: 426, subsections: [] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_iwork_science1: {
        id: "jhs_iwork_science1",
        title: "iワーク 中1理科",
        totalPages: 386,
        imagesPath: "images/jhs_iwork_science1/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_iwork_science1_cover.jpg",
        qrBase: "",
        chapters: [
            { id: "cover", title: "表紙", start: 1, end: 1, subsections: [] },
            { id: "main", title: "中1理科（本冊）", start: 2, end: 208, subsections: [
                { num: 1, title: "自然の中にあふれる生命", page: 5 },
                { num: 2, title: "花のつくり", page: 11 },
                { num: 3, title: "子葉、葉、根のつくり", page: 17 },
                { num: 4, title: "植物の分類", page: 21 },
                { num: 5, title: "背骨のある動物", page: 29 },
                { num: 6, title: "背骨のない動物と動物の分類", page: 33 },
                { num: 7, title: "身近な大地と地震のゆれ", page: 53 },
                { num: 8, title: "地震のゆれの大きさ", page: 59 },
                { num: 9, title: "火山の噴火", page: 67 },
                { num: 10, title: "マグマからできた岩石", page: 71 },
                { num: 11, title: "地層のでき方と広がり", page: 77 },
                { num: 12, title: "地層・化石と大地の歴史", page: 81 },
                { num: 13, title: "物質の区別", page: 103 },
                { num: 14, title: "重さ・体積と物質の区別", page: 107 },
                { num: 15, title: "いろいろな気体とその性質", page: 115 },
                { num: 16, title: "物質のとけ方", page: 121 },
                { num: 17, title: "溶質のとり出し方", page: 125 },
                { num: 18, title: "物質のすがたの変化", page: 133 },
                { num: 19, title: "状態変化と温度", page: 137 },
                { num: 20, title: "光の進み方", page: 159 },
                { num: 21, title: "光が通りぬけるときのようす", page: 163 },
                { num: 22, title: "レンズのはたらき", page: 169 },
                { num: 23, title: "音による現象", page: 177 },
                { num: 24, title: "力のはたらき", page: 183 },
                { num: 25, title: "力のつり合い", page: 189 },
                { num: "資料", title: "実験・観察の基本操作", page: 209 }
            ] },
            { id: "main_answers", title: "中1理科 解答解説", start: 209, end: 279, subsections: [] },
            { id: "plus", title: "iワークプラス", start: 280, end: 357, subsections: [] },
            { id: "plus_answers", title: "iワークプラス 解答解説", start: 358, end: 386, subsections: [] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_teiki_science1: {
        id: "jhs_teiki_science1",
        title: "定期テスト対策ワーク 理科 中1",
        totalPages: 148,
        imagesPath: "images/jhs_teiki_science1/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_teiki_science1_cover.jpg",
        qrBase: "",
        chapters: [
            { id: "main", title: "ワーク（本書）", start: 1, end: 148, subsections: [
                { num: 0, title: "表紙・目次", page: 1 },
                { num: 1, title: "小学校の復習①", page: 4 },
                { num: 2, title: "小学校の復習②", page: 5 },
                { num: 3, title: "小学校の復習③", page: 6 },
                { num: 4, title: "小学校の復習④", page: 7 },
                { num: 5, title: "自然の中にあふれる生命", page: 8 },
                { num: 6, title: "植物の特徴と分類(1)", page: 12 },
                { num: 7, title: "植物の特徴と分類(2)", page: 17 },
                { num: 8, title: "■重要事項のまとめ(1)", page: 21 },
                { num: 9, title: "■まとめテスト(1)", page: 22 },
                { num: 10, title: "動物の特徴と分類(1)", page: 24 },
                { num: 11, title: "動物の特徴と分類(2)", page: 29 },
                { num: 12, title: "■重要事項のまとめ(2)", page: 33 },
                { num: 13, title: "■まとめテスト(2)", page: 34 },
                { num: 14, title: "■チャレンジ問題", page: 36 },
                { num: 15, title: "身近な大地", page: 38 },
                { num: 16, title: "ゆれる大地", page: 42 },
                { num: 17, title: "■重要事項のまとめ(1)", page: 49 },
                { num: 18, title: "■まとめテスト(1)", page: 50 },
                { num: 19, title: "火をふく大地(1)", page: 52 },
                { num: 20, title: "火をふく大地(2)", page: 58 },
                { num: 21, title: "語る大地(1)", page: 62 },
                { num: 22, title: "語る大地(2)", page: 67 },
                { num: 23, title: "■重要事項のまとめ(2)", page: 71 },
                { num: 24, title: "■まとめテスト(2)", page: 72 },
                { num: 25, title: "■チャレンジ問題", page: 74 },
                { num: 26, title: "いろいろな物質とその性質", page: 76 },
                { num: 27, title: "いろいろな気体とその性質", page: 82 },
                { num: 28, title: "■重要事項のまとめ(1)", page: 87 },
                { num: 29, title: "■まとめテスト(1)", page: 88 },
                { num: 30, title: "水溶液の性質(1)", page: 90 },
                { num: 31, title: "水溶液の性質(2)", page: 96 },
                { num: 32, title: "物質のすがたとその変化", page: 101 },
                { num: 33, title: "■重要事項のまとめ(2)", page: 107 },
                { num: 34, title: "■まとめテスト(2)", page: 108 },
                { num: 35, title: "■チャレンジ問題", page: 110 },
                { num: 36, title: "光による現象(1)", page: 112 },
                { num: 37, title: "光による現象(2)", page: 118 },
                { num: 38, title: "■重要事項のまとめ(1)", page: 124 },
                { num: 39, title: "■まとめテスト(1)", page: 125 },
                { num: 40, title: "音による現象", page: 127 },
                { num: 41, title: "力による現象(1)", page: 133 },
                { num: 42, title: "力による現象(2)", page: 139 },
                { num: 43, title: "■重要事項のまとめ(2)", page: 143 },
                { num: 44, title: "■まとめテスト(2)", page: 144 },
                { num: 45, title: "■チャレンジ問題", page: 146 },
                { num: 46, title: "発展学習", page: 148 }
            ] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_teiki_science2: {
        id: "jhs_teiki_science2",
        title: "定期テスト対策ワーク 理科 中2",
        totalPages: 168,
        imagesPath: "images/jhs_teiki_science2/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_teiki_science2_cover.jpg",
        qrBase: "",
        chapters: [
            { id: "main", title: "ワーク（本書）", start: 1, end: 168, subsections: [
                { num: 0, title: "表紙・目次", page: 1 },
                { num: 1, title: "いろいろな生物とその共通点", page: 4 },
                { num: 2, title: "活きている地球", page: 8 },
                { num: 3, title: "身のまわりの物質", page: 12 },
                { num: 4, title: "光・音・力による現象", page: 16 },
                { num: 5, title: "生物の体をつくるもの", page: 20 },
                { num: 6, title: "植物の体のつくりとはたらき(1)", page: 24 },
                { num: 7, title: "植物の体のつくりとはたらき(2)", page: 29 },
                { num: 8, title: "■重要事項のまとめ(1)", page: 34 },
                { num: 9, title: "■まとめテスト(1)", page: 35 },
                { num: 10, title: "動物の体のつくりとはたらき(1)", page: 37 },
                { num: 11, title: "動物の体のつくりとはたらき(2)", page: 42 },
                { num: 12, title: "動物の行動のしくみ", page: 47 },
                { num: 13, title: "■重要事項のまとめ(2)", page: 51 },
                { num: 14, title: "■まとめテスト(2)", page: 52 },
                { num: 15, title: "■チャレンジ問題", page: 54 },
                { num: 16, title: "地球をとり巻く大気のようす", page: 56 },
                { num: 17, title: "空気中の水の変化", page: 62 },
                { num: 18, title: "■重要事項のまとめ(1)", page: 69 },
                { num: 19, title: "■まとめテスト(1)", page: 70 },
                { num: 20, title: "天気の変化と大気の動き", page: 72 },
                { num: 21, title: "大気の動きと日本の四季", page: 76 },
                { num: 22, title: "■重要事項のまとめ(2)", page: 81 },
                { num: 23, title: "■まとめテスト(2)", page: 82 },
                { num: 24, title: "■チャレンジ問題", page: 84 },
                { num: 25, title: "物質の成り立ち(1)", page: 86 },
                { num: 26, title: "物質の成り立ち(2)", page: 91 },
                { num: 27, title: "物質の表し方", page: 97 },
                { num: 28, title: "■重要事項のまとめ(1)", page: 102 },
                { num: 29, title: "■まとめテスト(1)", page: 103 },
                { num: 30, title: "さまざまな化学変化(1)", page: 105 },
                { num: 31, title: "さまざまな化学変化(2)", page: 110 },
                { num: 32, title: "化学変化と物質の質量", page: 115 },
                { num: 33, title: "■重要事項のまとめ(2)", page: 121 },
                { num: 34, title: "■まとめテスト(2)", page: 122 },
                { num: 35, title: "■チャレンジ問題", page: 124 },
                { num: 36, title: "電流の性質(1)", page: 126 },
                { num: 37, title: "電流の性質(2)", page: 131 },
                { num: 38, title: "電流の性質(3)", page: 137 },
                { num: 39, title: "■重要事項のまとめ(1)", page: 143 },
                { num: 40, title: "■まとめテスト(1)", page: 144 },
                { num: 41, title: "電流の正体", page: 146 },
                { num: 42, title: "電流と磁界(1)", page: 151 },
                { num: 43, title: "電流と磁界(2)", page: 156 },
                { num: 44, title: "■重要事項のまとめ(2)", page: 161 },
                { num: 45, title: "■まとめテスト(2)", page: 162 },
                { num: 46, title: "■チャレンジ問題", page: 164 },
                { num: 47, title: "発展学習", page: 166 }
            ] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_teiki_science3: {
        id: "jhs_teiki_science3",
        title: "定期テスト対策ワーク 理科 中3",
        totalPages: 168,
        imagesPath: "images/jhs_teiki_science3/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_teiki_science3_cover.jpg",
        qrBase: "",
        chapters: [
            { id: "main", title: "ワーク（本書）", start: 1, end: 168, subsections: [
                { num: 0, title: "表紙・目次", page: 1 },
                { num: 1, title: "いろいろな生物とその共通点", page: 4 },
                { num: 2, title: "活きている地球", page: 8 },
                { num: 3, title: "身のまわりの物質", page: 12 },
                { num: 4, title: "光・音・力による現象", page: 16 },
                { num: 5, title: "生物の体のつくりとはたらき", page: 20 },
                { num: 6, title: "地球の大気と天気の変化", page: 24 },
                { num: 7, title: "化学変化と原子・分子", page: 28 },
                { num: 8, title: "電流とその利用", page: 32 },
                { num: 9, title: "生物のふえ方と成長", page: 36 },
                { num: 10, title: "遺伝の規則性と遺伝子", page: 41 },
                { num: 11, title: "生物の種類の多様性と進化", page: 45 },
                { num: 12, title: "■重要事項のまとめ", page: 49 },
                { num: 13, title: "■まとめテスト", page: 50 },
                { num: 14, title: "■チャレンジ問題", page: 52 },
                { num: 15, title: "宇宙の天体", page: 54 },
                { num: 16, title: "太陽と恒星の動き(1)", page: 59 },
                { num: 17, title: "■重要事項のまとめ(1)", page: 64 },
                { num: 18, title: "■まとめテスト(1)", page: 65 },
                { num: 19, title: "太陽と恒星の動き(2)", page: 67 },
                { num: 20, title: "月と金星の動きと見え方", page: 73 },
                { num: 21, title: "■重要事項のまとめ(2)", page: 77 },
                { num: 22, title: "■まとめテスト(2)", page: 78 },
                { num: 23, title: "■チャレンジ問題", page: 80 },
                { num: 24, title: "水溶液とイオン", page: 82 },
                { num: 25, title: "電池とイオン", page: 88 },
                { num: 26, title: "■重要事項のまとめ(1)", page: 94 },
                { num: 27, title: "■まとめテスト(1)", page: 95 },
                { num: 28, title: "酸・アルカリと塩(1)", page: 97 },
                { num: 29, title: "酸・アルカリと塩(2)", page: 101 },
                { num: 30, title: "■重要事項のまとめ(2)", page: 105 },
                { num: 31, title: "■まとめテスト(2)", page: 106 },
                { num: 32, title: "■チャレンジ問題", page: 108 },
                { num: 33, title: "力の合成と分解", page: 110 },
                { num: 34, title: "物体の運動(1)", page: 117 },
                { num: 35, title: "物体の運動(2)", page: 122 },
                { num: 36, title: "■重要事項のまとめ(1)", page: 126 },
                { num: 37, title: "■まとめテスト(1)", page: 127 },
                { num: 38, title: "仕事とエネルギー", page: 129 },
                { num: 39, title: "多様なエネルギーとその移り変わり", page: 135 },
                { num: 40, title: "エネルギー資源とその利用", page: 139 },
                { num: 41, title: "■重要事項のまとめ(2)", page: 143 },
                { num: 42, title: "■まとめテスト(2)", page: 144 },
                { num: 43, title: "■チャレンジ問題", page: 146 },
                { num: 44, title: "自然界のつり合い", page: 148 },
                { num: 45, title: "さまざまな物質の利用と人間／科学技術の発展", page: 154 },
                { num: 46, title: "人間と環境／持続可能な社会をめざして", page: 159 },
                { num: 47, title: "■重要事項のまとめ", page: 163 },
                { num: 48, title: "■まとめテスト", page: 164 },
                { num: 49, title: "■チャレンジ問題", page: 165 },
                { num: 50, title: "発展学習", page: 166 }
            ] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_iwork_math1: {
        id: "jhs_iwork_math1",
        title: "iワーク 中1数学",
        totalPages: 459,
        imagesPath: "images/jhs_iwork_math1/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_iwork_math1_cover.png",
        qrBase: "",
        chapters: [
            { id: "cover", title: "表紙", start: 1, end: 1, subsections: [] },
            { id: "main", title: "中1数学（本冊）", start: 2, end: 225, subsections: [
                { num: 1, title: "正の数・負の数", page: 11 },
                { num: 2, title: "正の数・負の数の加法，減法", page: 17 },
                { num: 3, title: "正の数・負の数の乗法，除法", page: 23 },
                { num: 4, title: "乗法と除法の混じった計算", page: 27 },
                { num: 5, title: "いろいろな計算", page: 31 },
                { num: 6, title: "文字を使った式", page: 51 },
                { num: 7, title: "文字式の加法，減法", page: 59 },
                { num: 8, title: "文字式と数の乗法，除法", page: 63 },
                { num: 9, title: "関係を表す式", page: 67 },
                { num: 10, title: "方程式とその解", page: 81 },
                { num: 11, title: "いろいろな方程式", page: 85 },
                { num: 12, title: "方程式の利用(1)", page: 91 },
                { num: 13, title: "方程式の利用(2)", page: 95 },
                { num: 14, title: "関数・比例", page: 111 },
                { num: 15, title: "比例のグラフ", page: 117 },
                { num: 16, title: "反比例", page: 121 },
                { num: 17, title: "比例，反比例の利用", page: 125 },
                { num: 18, title: "直線と図形，移動", page: 139 },
                { num: 19, title: "基本の作図", page: 145 },
                { num: 20, title: "円とおうぎ形", page: 151 },
                { num: 21, title: "いろいろな立体", page: 165 },
                { num: 22, title: "空間内の位置関係", page: 171 },
                { num: 23, title: "体積・表面積", page: 177 },
                { num: 24, title: "データの活用", page: 193 }
            ] },
            { id: "main_answers", title: "中1数学 解答解説", start: 226, end: 338, subsections: [] },
            { id: "plus", title: "iワークプラス", start: 339, end: 415, subsections: [] },
            { id: "plus_answers", title: "iワークプラス 解答解説", start: 416, end: 459, subsections: [] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_iwork_math2: {
        id: "jhs_iwork_math2",
        title: "iワーク 中2数学",
        totalPages: 473,
        imagesPath: "images/jhs_iwork_math2/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_iwork_math2_cover.png",
        qrBase: "",
        chapters: [
            { id: "cover", title: "表紙", start: 1, end: 1, subsections: [] },
            { id: "main", title: "中2数学（本冊）", start: 2, end: 233, subsections: [
                { num: 1, title: "式の加法，減法", page: 9 },
                { num: 2, title: "単項式・多項式の計算", page: 13 },
                { num: 3, title: "文字式の利用", page: 21 },
                { num: 4, title: "連立方程式の解法(1)", page: 41 },
                { num: 5, title: "連立方程式の解法(2)", page: 47 },
                { num: 6, title: "連立方程式の利用(1)", page: 53 },
                { num: 7, title: "連立方程式の利用(2)", page: 59 },
                { num: 8, title: "一次関数とグラフ", page: 79 },
                { num: 9, title: "一次関数の式", page: 87 },
                { num: 10, title: "一次関数と方程式", page: 93 },
                { num: 11, title: "一次関数の利用", page: 97 },
                { num: 12, title: "直線と図形", page: 101 },
                { num: 13, title: "角と平行線，多角形の角", page: 119 },
                { num: 14, title: "角の大きさの求め方", page: 127 },
                { num: 15, title: "証明", page: 131 },
                { num: 16, title: "二等辺三角形", page: 145 },
                { num: 17, title: "直角三角形", page: 151 },
                { num: 18, title: "平行四辺形", page: 155 },
                { num: 19, title: "特別な平行四辺形", page: 161 },
                { num: 20, title: "平行線と面積", page: 165 },
                { num: 21, title: "方程式と図形", page: 169 },
                { num: 22, title: "確率", page: 185 },
                { num: 23, title: "確率の利用", page: 191 },
                { num: 24, title: "箱ひげ図", page: 197 }
            ] },
            { id: "main_answers", title: "中2数学 解答解説", start: 234, end: 353, subsections: [] },
            { id: "plus", title: "iワークプラス", start: 354, end: 430, subsections: [] },
            { id: "plus_answers", title: "iワークプラス 解答解説", start: 431, end: 473, subsections: [] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    },
    jhs_iwork_math3: {
        id: "jhs_iwork_math3",
        title: "iワーク 中3数学",
        totalPages: 526,
        imagesPath: "images/jhs_iwork_math3/",
        printImagesPath: null,
        spreadEvenLeftBySection: true,
        coverImage: "images/jhs_iwork_math3_cover.png",
        qrBase: "",
        chapters: [
            { id: "cover", title: "表紙", start: 1, end: 1, subsections: [] },
            { id: "main", title: "中3数学（本冊）", start: 2, end: 257, subsections: [
                { num: 1, title: "式の展開", page: 9 },
                { num: 2, title: "因数分解", page: 21 },
                { num: 3, title: "いろいろな因数分解", page: 27 },
                { num: 4, title: "式の計算の利用", page: 31 },
                { num: 5, title: "平方根", page: 45 },
                { num: 6, title: "根号をふくむ式の計算(1)", page: 53 },
                { num: 7, title: "根号をふくむ式の計算(2)", page: 59 },
                { num: 8, title: "二次方程式とその解き方", page: 79 },
                { num: 9, title: "二次方程式の解き方", page: 83 },
                { num: 10, title: "二次方程式の利用", page: 91 },
                { num: 11, title: "関数 y=ax² とグラフ", page: 111 },
                { num: 12, title: "いろいろな事象と関数の利用", page: 119 },
                { num: 13, title: "2乗に比例する関数と図形", page: 125 },
                { num: 14, title: "相似な図形", page: 143 },
                { num: 15, title: "平行線と線分の比", page: 149 },
                { num: 16, title: "相似な図形の計量", page: 157 },
                { num: 17, title: "相似の利用", page: 161 },
                { num: 18, title: "円周角の定理", page: 177 },
                { num: 19, title: "三平方の定理", page: 195 },
                { num: 20, title: "三平方の定理の利用(1)", page: 203 },
                { num: 21, title: "三平方の定理の利用(2)", page: 209 },
                { num: 22, title: "空間図形と三平方の定理(1)", page: 213 },
                { num: 23, title: "空間図形と三平方の定理(2)", page: 221 },
                { num: 24, title: "標本調査", page: 237 }
            ] },
            { id: "main_answers", title: "中3数学 解答解説", start: 258, end: 401, subsections: [] },
            { id: "plus", title: "iワークプラス", start: 402, end: 478, subsections: [] },
            { id: "plus_answers", title: "iワークプラス 解答解説", start: 479, end: 526, subsections: [] }
        ],
        get sections() {
            return this.chapters.map(ch => ({
                id: ch.id, title: ch.title, start: ch.start, end: ch.end,
                pages: ch.end - ch.start + 1
            }));
        },
        pageQrs: {}
    }
};

if (typeof module !== "undefined" && module.exports) {
    module.exports = { jhsData };
}
